insert into products values (1, 'Intel', 'chip', 'chip', 'i7', null, null);
insert into assets values (1, 1, 'chip', null, null);
insert into vehicles values (1, 1);
insert into facilities values (1, null, 'DC', 'Washington, DC');
insert into facilities values (2, null, 'Augusta', 'Augusta, GA');
insert into asset_at values (1, 1, null, null);
insert into convoys values (1, 'Please', 1, 2, null, null);
insert into used_by values (1, 1);
insert into asset_on values (1, 1, null, null);
insert into users values (1, 'Brian', TRUE);
insert into roles values (1, 'Baller');
insert into user_is values (1, 1);
insert into user_supports values (1, 1);
insert into levels values (1, 'tss', 'Top Secret Guys... shhhh');
insert into compartments values (1, 'tstst', 'This is a nice compartment');
insert into security_tags values (1, 1, 1, 1, 1, 1);